Module Module1\n    Sub Main()\n        Try\n            foo()\n        Catch ex As Exception\n            ' Handle exception at a higher level\n            Console.WriteLine("An error occurred: " & ex.Message)\n        End Try\n    End Sub\n\n    Private Sub foo()\n        Try\n            ' Do something\n        Catch ex As Exception\n            ' Optionally log or handle the exception\n            Throw\n        End Try\n    End Sub\nEnd Module