catch(Exception ex)\n{\n     //error handling\n}