using System;\nusing System.Windows.Forms;\n\nclass Program\n{\n    static void Main(string[] args)\n    {\n        Application.ThreadException += new ThreadExceptionEventHandler(Application_ThreadException);\n        AppDomain.CurrentDomain.UnhandledException += new UnhandledExceptionEventHandler(CurrentDomain_UnhandledException);\n\n        try\n        {\n            throw new Exception("Test exception");\n        }\n        catch (Exception ex)\n        {\n            Console.WriteLine("Caught exception: " + ex.Message);\n        }\n    }\n\n    static void Application_ThreadException(object sender, ThreadExceptionEventArgs e)\n    {\n        Console.WriteLine("Thread exception: " + e.Exception.Message);\n    }\n\n    static void CurrentDomain_UnhandledException(object sender, UnhandledExceptionEventArgs e)\n    {\n        Console.WriteLine("Unhandled exception: " + e.ExceptionObject);\n        e.Handled = true;\n    }\n}